# Demo: Discrete Hopfield Nerual Network as CAM

## 1. Storage

$$W=\frac{1}{N}\sum_{\mu=1}^M\xi_\mu \xi_mu^T - MI$$
where $w_{ii} = 0$

// HAVE NOT COMPLETED

In [1]:
import numpy as np
from random import choice

class Hopfield:
    
    def __init__(self, dim_target):
        self._dim_target = dim_target
        self._weight = np.zeros((dim_target, dim_target))
        
    def storage(self, num_target, mat_target):
        for i in range(num_target):
            xi = np.transpose(mat_target[i,:])
            self._weight += xi * np.transpose(xi) / num_target     
        for i in range(self._dim_target):
            self._weight[i,i] = 0
            
    def retrieve(self, probe):
        output = probe
        unchange_time = 0
        while unchange_time < 10:
            j = choice(range(self._dim_target))
            old = output[0, j]
            temp = self._weight[j,:] * np.transpose(np.matrix([output[0, j]] * self._dim_target))
            if temp > 0:
                output[0, j] = 1
            elif temp < 0:
                output[0, j] = -1
            if old == output[0, j]:
                unchange_time += 1
            else:
                unchange_time = 0
        return output

In [2]:
sample = np.matrix([[-1, 1, -1], [-1, -1, 1]])
print('Sample: \n{}'.format(sample))
hnn = Hopfield(3)
hnn.storage(2, sample)

probe = np.matrix([[-1, 1, 1]])
print('Probe: \n{}'.format(probe))

output = hnn.retrieve(probe)
print('Output: \n{}'.format(output))

Sample: 
[[-1  1 -1]
 [-1 -1  1]]
Probe: 
[[-1  1  1]]
Output: 
[[-1  1 -1]]
