## Reference
Problem:

http://mnemstudio.org/path-finding-q-learning-tutorial.htm [Original: Failed to Connect]

http://blog.csdn.net/yangziluomu/article/details/50748086 [Translation]

Reward Matrix

'-1' denoting that no connection between nodes.

In [1]:
import numpy as np

reward_matrix = np.matrix([[-1, -1, -1, -1, 0, -1],
                          [-1, -1, -1, 0, -1, 100],
                          [-1, -1, -1, 0, -1, -1],
                          [-1, 0, 0, -1, 0, -1],
                          [0, -1, -1, 0, -1, 100],
                          [-1, 0, -1, -1, 0, 100]])
print('Reward Matrix:\n', reward_matrix)

Reward Matrix:
 [[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1   0  -1]
 [  0  -1  -1   0  -1 100]
 [ -1   0  -1  -1   0 100]]


$$\Delta Q(s,a)=R(s,a)+\gamma\cdot\max_{\tilde{a}}{Q(\tilde{s},\tilde{a})}$$

$$Q(s,a) = (1-\alpha)Q(s,a)+\alpha\Delta Q(s,a)$$

In [2]:
from random import choice
def learn_illustrate(Q, R, learning_rate, alpha_rate):
    status = R.shape[1]
    
    # Select initial status randomly.
    present_status = choice(range(0, status,1))
    
    while present_status != 5: # While present status is not terminal status
        avaliable_status  = [i for i,j in enumerate(R[present_status, :].tolist()[0]) if float(j) >= 0]
        next_action = choice(avaliable_status)
        delta_Q = R[present_status, next_action] + learning_rate * max(Q[next_action])
        Q[present_status, next_action] = (1-alpha_rate) * Q[present_status, next_action] + alpha_rate * delta_Q
        print('{} --> {}\n'.format(present_status, next_action))
        present_status = next_action    
    return Q

Q = np.zeros((6, 6))

# First iteration
learn_illustrate(Q, reward_matrix, 0.6, 0.2)

4 --> 3

3 --> 1

1 --> 5



array([[  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,  80.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.]])

现在我们进行正式的训练，迭代次数为20次。

In [6]:
def learn(Q, R, learning_rate, alpha_rate):
    status = R.shape[1]
    
    # Select initial status randomly.
    present_status = choice(range(0, status,1))
    
    while present_status != 5: # While present status is not terminal status
        avaliable_status  = [i for i,j in enumerate(R[present_status, :].tolist()[0]) if float(j) >= 0]
        next_action = choice(avaliable_status)
        delta_Q = R[present_status, next_action] + learning_rate * max(  Q[next_action])
        Q[present_status, next_action] = (1-alpha_rate) * Q[present_status, next_action] + alpha_rate * delta_Q
        present_status = next_action    
    return Q

i = 1
Q = np.zeros((6, 6))
while i <= 400:
    Q = learn(Q, reward_matrix, 0.8, 0.2)
    i += 1
print(Q)

[[   0.     0.     0.     0.    80.     0. ]
 [   0.     0.     0.    64.     0.   100. ]
 [   0.     0.     0.    64.     0.     0. ]
 [   0.    80.    51.2    0.    80.     0. ]
 [  64.     0.     0.    64.     0.   100. ]
 [   0.     0.     0.     0.     0.     0. ]]


最优路径:

>       2->3->4->5
       